# runs all make funtions on every git push

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run Test
        run: |
          make requirements
          make dev-setup
          make run-checks
      