name: de-lambda-legends-project

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # - name: Set up venv
      #   run: python -m venv venv && source venv/bin/activate
      - name: Run Test
        run: |
          make requirements
          make dev-setup
          make run-checks

  deploy-lambda:
    name: deploy-lambda
    runs-on: ubuntu-latest
    environment: development
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Creation
        working-directory: terraform
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve